<h1><?php echo $this->translate('Posts'); ?></h1>
<?php if (!empty ($this->paginator)) : ?>
    <?php foreach ($this->paginator as $post) : ?>
        <?php /** @var \Blog\Entity\Post $post */ ?>
        <?php $postedAt = $this->dateFormat(
                $post->getCreated(),
                IntlDateFormatter::MEDIUM, // Date
                IntlDateFormatter::MEDIUM, // Time
                'en_US'
        ); ?>
        <h1><?php echo $post->getCategory()->getSlug() ?></h1>
        <h2>
            <a href="<?php echo $this->url('display-post', [
                    'categorySlug' => $post->getCategory()->getSlug(),
                    'postSlug' => $post->getSlug()
        ]); ?>">
                <?php echo $this->escapeHtml($post->getTitle()); ?>
            </a>
        </h2>
        <br />
        <?php echo sprintf($this->translate('Posted on %s in the %s category'), $postedAt,
                $this->escapeHtml($post->getCategory()->getName())); ?>
        <hr />
    <?php endforeach; ?>

    <?php

    echo $this->paginationControl($this->paginator,
        'Sliding',
        'partial/pagination',
        ['route' => 'blog/paged']
    );
    ?>
<?php else : ?>
    <p><?php echo $this->translate('There are currently no posts.'); ?></p>
<?php endif; ?>
