<h1><?php echo $this->translate('Posts'); ?></h1>
<?php if (!empty ($this->posts)) : ?>
    <?php foreach ($this->posts as $post) : ?>
        <?php /** @var \Blog\Entity\Post $post */ ?>
        <strong>ID: </strong> <?php echo $this->escapeHtml($post->getId()); ?>
        <br />
        <strong>Title: </strong> <?php echo $this->escapeHtml($post->getTitle()); ?>
        <br />
        <strong>Category: </strong> <?php echo $this->escapeHtml($post->getCategory()->getName()); ?>
        <br />
        <strong>Content: </strong> <?php echo $this->escapeHtml($post->getContent()); ?>
        <br />
        <?php echo nl2br($this->escapeHtml($post->getContent())); ?>
        <hr />
    <?php endforeach; ?>
<?php else : ?>
    <p><?php echo $this->translate('There are currently no posts.'); ?></p>
<?php endif; ?>
