<?php /** @var \Blog\Entity\Post $post */ ?>
<?php $post = $this->post; ?>

<?php $postedAt = $this->dateFormat(
    $post->getCreated(),
    IntlDateFormatter::MEDIUM, // Date
    IntlDateFormatter::MEDIUM, // Time
    'en_US'
); ?>

<h1>
    <?php echo $this->escapeHtml($post->getTitle()); ?> (<a href="<?php echo $this->url('edit', ['postId' => $post->getId()]) ?>">Edit</a>
    - <a href="<?php echo $this->url('delete', ['postId' => $post->getId()]) ?>">Delete</a>)
</h1>

<?php echo sprintf($this->translate('Posted on %s'), $postedAt); ?>
<br /><br />

<p><?php echo nl2br($this->escapeHtml($post->getContent())) ?></p>

<strong><?php echo $this->translate('Category'); ?></strong> <?php echo $this->escapeHtml($post->getCategory()->getName()); ?>
